language: cpp

compiler: gcc

cache: apt

env:
    matrix:
        - WITH_CUDA=false

before_install:
    - export NUM_THREADS=4
    - export VER=0.1

install:
    # - sudo -E ./travis-scripts/get-openblas.sh
    - sudo -E ./travis-scripts/suite_deps.sh

before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64:/usr/lib
    - export PATH=/home/travis/miniconda/bin:$PATH

script: cd sirius-suite/ && make
