language: cpp

compiler: gcc

cache: apt

env:
    - WITH_CUDA=false
    - WITH_OPENCV=false
    - WITH_SUITE=true
    - WITH_APP=true

before_install:
    - export NUM_THREADS=4
    - export VER=0.1

install:
    - if $WITH_SUITE; then sudo -E ./travis-scripts/suite_deps.sh; fi

before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64:/usr/lib
    - export PATH=/home/travis/miniconda/bin:$PATH

script:
    - cd sirius-suite && make && cd -;
