language: cpp

compiler: gcc

cache: apt

sudo: true

dist: trusty

env:
    global:
        - THRIFT=`pwd`/thrift-0.9.2
        - CAFFE=`pwd`/tools/caffe/distribute
        - LUCIDAROOT=`pwd`/lucida

before_install:
    - sudo apt-get install -y python-software-properties;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install -y gcc-4.8 g++-4.8;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50;

install:
    make local
